const StoreData = [
  { id: 0, src: "store1.png", alt: "store" },
  { id: 1, src: "store2.png", alt: "store" },
  { id: 2, src: "store1.png", alt: "store" },
  { id: 3, src: "store2.png", alt: "store" },
];

const StoryData = [
  { id: 0, src: "stories.jpg", alt: "stories circle" },
  { id: 1, src: "stories.jpg", alt: "stories circle" },
  { id: 2, src: "stories.jpg", alt: "stories circle" },
  { id: 3, src: "stories.jpg", alt: "stories circle" },
  { id: 4, src: "stories.jpg", alt: "stories circle" },
  { id: 5, src: "stories.jpg", alt: "stories circle" },
  { id: 6, src: "stories.jpg", alt: "stories circle" },
  { id: 7, src: "stories.jpg", alt: "stories circle" },
  { id: 8, src: "stories.jpg", alt: "stories circle" },
];

const TrendingData = [
  { id: 0, src: "trendingItem.png", alt: "trendingItem" },
  { id: 1, src: "trendingItem.png", alt: "trendingItem" },
  { id: 2, src: "trendingItem.png", alt: "trendingItem" },
  { id: 3, src: "trendingItem.png", alt: "trendingItem" },
  { id: 4, src: "trendingItem.png", alt: "trendingItem" },
];

const DiscountBarData = [
  { id: 0, src: "appBanner.png", alt: "app banner" },
  { id: 1, src: "discountBanner.png", alt: "app banner" },
];

const TopOfferData = [
  { id: 0, src: "discount1.png", alt: "discount" },
  { id: 1, src: "discount2.png", alt: "discount" },
  { id: 2, src: "discount1.png", alt: "discount" },
  { id: 3, src: "discount2.png", alt: "discount" },
];

const CategoryData = [
  { id: 0, src: "category1.png", alt: "category" },
  { id: 1, src: "category2.png", alt: "category" },
  { id: 2, src: "category3.png", alt: "category" },
  { id: 3, src: "category1.png", alt: "category" },
  { id: 4, src: "category2.png", alt: "category" },
  { id: 5, src: "category3.png", alt: "category" },
  { id: 6, src: "category1.png", alt: "category" },
  { id: 7, src: "category2.png", alt: "category" },
  { id: 8, src: "category3.png", alt: "category" },
  { id: 9, src: "category1.png", alt: "category" },
  { id: 10, src: "category2.png", alt: "category" },
  { id: 11, src: "category3.png", alt: "category" },
];

const DiscountBannerData = [
  { id: 0, src: "discountBanner.png", alt: "discountBanner" },
];

const AboutData = [
  { id: 0, src: "pickup.png", alt: "about banner" },
  { id: 1, src: "delivery.png", alt: "about banner" },
];

const StoreSearchData = [
  {
    id: 0,
    src: "store2.png",
    alt: "Store Info",
    address_line_one: "2nd Floor, K-Tech NASSCOM, 67, Phase 3,",
    address_line_two: "1st Sector, HSR Layout, Bengaluru,",
    address_line_three: "Karnataka 560102",
    contact: "75063326420",
    rating: "rating.png",
    distance: "4.2km",
    name: "Rahul Stores",
    product: [
      {
        id: 0,
        src: "product1.png",
        alt: "product",
        name: "Masala Lays",
        weight: "50 gm",
        price: "$20",
      },
      {
        id: 1,
        src: "product2.png",
        alt: "product",
        name: "Veggie Fingers",
        weight: "250 gm",
        price: "$120",
      },
      {
        id: 2,
        src: "product3.png",
        alt: "product",
        name: "Harpic Cleaner",
        weight: "500 ml",
        price: "$220",
      },
    ],
  },
  {
    id: 1,
    src: "store2.png",
    alt: "Store Info",
    address_line_one: "2nd Floor, K-Tech NASSCOM, 67, Phase 3,",
    address_line_two: "1st Sector, HSR Layout, Bengaluru,",
    address_line_three: "Karnataka 560102",
    contact: "75063326420",
    rating: "rating.png",
    distance: "4.2km",
    name: "Rahul Stores",
    product: [
      {
        id: 0,
        src: "product1.png",
        alt: "product",
        name: "Masala Lays",
        weight: "50 gm",
        price: "$20",
      },
      {
        id: 1,
        src: "product2.png",
        alt: "product",
        name: "Veggie Fingers",
        weight: "250 gm",
        price: "$120",
      },
      {
        id: 2,
        src: "product3.png",
        alt: "product",
        name: "Harpic Cleaner",
        weight: "500 ml",
        price: "$220",
      },
    ],
  },
  {
    id: 2,
    src: "store2.png",
    alt: "Store Info",
    address_line_one: "2nd Floor, K-Tech NASSCOM, 67, Phase 3,",
    address_line_two: "1st Sector, HSR Layout, Bengaluru,",
    address_line_three: "Karnataka 560102",
    contact: "75063326420",
    rating: "rating.png",
    distance: "4.2km",
    name: "Rahul Stores",
    product: [
      {
        id: 0,
        src: "product1.png",
        alt: "product",
        name: "Masala Lays",
        weight: "50 gm",
        price: "$20",
      },
      {
        id: 1,
        src: "product2.png",
        alt: "product",
        name: "Veggie Fingers",
        weight: "250 gm",
        price: "$120",
      },
      {
        id: 2,
        src: "product3.png",
        alt: "product",
        name: "Harpic Cleaner",
        weight: "500 ml",
        price: "$220",
      },
    ],
  },
  {
    id: 3,
    src: "store2.png",
    alt: "Store Info",
    address_line_one: "2nd Floor, K-Tech NASSCOM, 67, Phase 3,",
    address_line_two: "1st Sector, HSR Layout, Bengaluru,",
    address_line_three: "Karnataka 560102",
    contact: "75063326420",
    rating: "rating.png",
    distance: "4.2km",
    name: "Rahul Stores",
    product: [
      {
        id: 0,
        src: "product1.png",
        alt: "product",
        name: "Masala Lays",
        weight: "50 gm",
        price: "$20",
      },
      {
        id: 1,
        src: "product2.png",
        alt: "product",
        name: "Veggie Fingers",
        weight: "250 gm",
        price: "$120",
      },
      {
        id: 2,
        src: "product3.png",
        alt: "product",
        name: "Harpic Cleaner",
        weight: "500 ml",
        price: "$220",
      },
    ],
  },
  {
    id: 4,
    src: "store2.png",
    alt: "Store Info",
    address_line_one: "2nd Floor, K-Tech NASSCOM, 67, Phase 3,",
    address_line_two: "1st Sector, HSR Layout, Bengaluru,",
    address_line_three: "Karnataka 560102",
    contact: "75063326420",
    rating: "rating.png",
    distance: "4.2km",
    name: "Rahul Stores",
    product: [
      {
        id: 0,
        src: "product1.png",
        alt: "product",
        name: "Masala Lays",
        weight: "50 gm",
        price: "$20",
      },
      {
        id: 1,
        src: "product2.png",
        alt: "product",
        name: "Veggie Fingers",
        weight: "250 gm",
        price: "$120",
      },
      {
        id: 2,
        src: "product3.png",
        alt: "product",
        name: "Harpic Cleaner",
        weight: "500 ml",
        price: "$220",
      },
    ],
  },
  {
    id: 5,
    src: "store2.png",
    alt: "Store Info",
    address_line_one: "2nd Floor, K-Tech NASSCOM, 67, Phase 3,",
    address_line_two: "1st Sector, HSR Layout, Bengaluru,",
    address_line_three: "Karnataka 560102",
    contact: "75063326420",
    rating: "rating.png",
    distance: "4.2km",
    name: "Rahul Stores",
    product: [
      {
        id: 0,
        src: "product1.png",
        alt: "product",
        name: "Masala Lays",
        weight: "50 gm",
        price: "$20",
      },
      {
        id: 1,
        src: "product2.png",
        alt: "product",
        name: "Veggie Fingers",
        weight: "250 gm",
        price: "$120",
      },
      {
        id: 2,
        src: "product3.png",
        alt: "product",
        name: "Harpic Cleaner",
        weight: "500 ml",
        price: "$220",
      },
    ],
  },
];

export {
  TrendingData,
  StoryData,
  StoreData,
  DiscountBarData,
  TopOfferData,
  CategoryData,
  DiscountBannerData,
  AboutData,
  StoreSearchData,
};
